version: "3.7"
services:
    #php Service
    php:
        build:
            context: .
            dockerfile: Dockerfile
            target: php
            args:
                - APP_ENV=${APP_ENV}
        container_name: php
        restart: always
        volumes:
            - ./:/var/www
        ports:
            - "8001:8000"
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        depends_on:
            - db
            - redis

    #Database
    db:
        image: mysql:8.3
        container_name: db
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
    # redis server
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
        ports:
            - "6379:6379"
volumes:
    db_data: ~
